apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:l0KVNXaZcrnmB/aDpKVDT//q3fp9KtHGEEBy45YZIs7jH3G1,iv:fwzSkCWTiZrVUyi9d1oOZKa+87i5OvwohUY7AdJXlws=,tag:8epATmS2I/p5SRFwrSFqbA==,type:str]
    credentials.json: ENC[AES256_GCM,data:9EKX+Ys8rDcAnZvzYcnahqfIow9kzjJSER8C0I6jh7vpzGFaZLoZBMTnNtlKJH4/uAqd5GPXWFGIy+93n/rZT0CoKjHwWLSP7F7LA03vwKPHmq16beSdLzLBqPEc7BPCzoowioW+vH6l//FooTYDfK0QVR4r4xbOSbE2H73y61EG4nrW8wer2DrXBNszbcue//GIk0c0pNVXtr3kgmAVzPg0kvQz+BncJUOIpudNnA==,iv:mBnNUcz2ShJPzgbxWKSGdUWDIgX2ALPsr7iNxcpZwWg=,tag:0K55ZMFlV1adJ8ajGsQGbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY3BKWU5STlNJQ1c5RXRR
            TUM0MU5FNHpTaDNCZGhSSlBFV042b1NBem1rCnM1ZTN3a1FhSGFaM0cyTXZJc1dS
            czBSMXZXVVUyNTlHUGNKZGNjeC95dlUKLS0tIENYU3hUa3hvM0M0MXJoUldydVRV
            bGtzbkRqcEZRNHcrT001bU5vN1VrbVEKZcrlwr9CieqAA3DfY6ImuP6qndxmUXME
            NXxvDaaTkL1O11Qz1OwNM4lWQfn4WV1JJYH4uss8nIJPdfOrInlc9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T01:53:36Z"
    mac: ENC[AES256_GCM,data:pzBw/qnp3YnxXuPZj+yEcCeT2X3VjPtIIyOQSlU1L6W2LyuNoVCLkFEheKau/UTYCc6BzI15phj6dczOIT86rLMeq84354NuskE7WJ3sgj+ARt/isBgGkBfTIPD7LE8CPSD7p8QeDToB2rywtJG5dXo6q92GmcAoju/MZDfCyOs=,iv:pckFg1HR3ksRqFIfFBUdPutuU8heb+289tWuGRvQttg=,tag:C4NF5+QC6AEy0N+U13Lq4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
