apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:SK+9uRLQ5rmsGGkY6VTEw/+kc87YGA9A8/LHnzahTBEsqhYU,iv:dJlo/K2Xn0S8VUhtkplSPY3x7Pzjy2GT/gYIiScW9GA=,tag:YdVZhFHuUpCxhXvihQDojA==,type:str]
    credentials.json: ENC[AES256_GCM,data:ZiLBS1LiGt6uP+79+nVEMHHqlL7JPGZJdzsZnHsqYJbh46sWJUNDK7P4yMmdn88+i/LJDtHtSHCnjjAzm31h8gxF3j/CDkGI3zMj+KPnCAYvw9PsA7x0ZigzXH613ijLgnp4b9ejAimfqeSLl0SIAiH4R+JyEVBZMfUB1hEkU9TdnP+cKJD/yg7j4a1d5qL8GPKYKjDrQcQ5ZeKqmV/7uwOZCs+9aS2glUCXDTMo7w==,iv:rzf2EZtwbqTcfUYJRaV+al9xQD98BvxeXPvAOxA/Jfs=,tag:oxeWWynrWz2oppS8hfaePQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmKzRnT01GbVlXaGFwM0lN
            bllDY3RtcXM1V0tPaFROb1JXYTdrSFRKQzBjCkJ1U0ZpbXhmWUN3VVNCYVpMeHor
            V2VSTzhSTHdoOXZKUy93UGxkSGNzWHcKLS0tIEJlc1FucVZpcTBqdllKdHVBVCtY
            OHRobjlOeENHQjJvdlg3ckFoZlltcWsKbCYYJBzV3ap5zf/O632ge0g0NXQdOq9K
            SanlJ36fwHMcOT/Bu9nDWBSngEOrMHMHapxEAU6g492aRR/LmdROHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T20:18:38Z"
    mac: ENC[AES256_GCM,data:QnoYO40g/4BvivKF/S3ckgY0ZPm3CxgfI1GFSrS7y+w80IJILpSCWQa7HbNK+fD7figzeXvKqBW1/djyg/n12IhsAtJG4gGCLkjpGjdA47hWs1Qs6R5m6mcjIKGjrmZ+h8XzZkyXXzDpa9g8Fhvh8sb/7/pYwXg7xc+SvgyhEqM=,iv:TGJFRPm5SmD62O52LSH1BF6PxlXRatiNn1P7X1hotpA=,tag:k3KYhSCxLP9ybYcLCaATOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
