apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:r3BWZGjxfcJmLiApgV92TWP/pfYdOYFdcgOm92wCk3MceHYl,iv:Rnjc0eNw3tnZKM8MYIF1K3Qu7PitJYZ50sqvxhagubw=,tag:Wc8b59+/YqOroC8/K7EVBQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:ELcOqXXvBN8/e+Eo3j3AIjsC4IN+sWmIkQjlcTL8nkJ3j7QuaABmqSKArOcefeCbqjG/E4k/GG+19ohGJh1eXuBw6aG9yTcPMKA2Dx+OX8KXFCGnhGtao1Ils1bXKlmvyS0fnis6rr1p6YvhPuS/hzGLNkHe6eMADzDHIrHDAI1wBepdNWROHaRkDRQebwkXAujiRFhgJVTyJfI6PhDN9yrFHFd6cA7BDlBTSHSXfg==,iv:q/ruPnvogoehAO10DdBLMdjJsKassDTzxqGrCT7DV7o=,tag:mJfUKBamizb8husH0YH+xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRzVlb0xUU3lWSjhyOC91
            dWVYbDcwVWVWOHNONU5SLy9odFdHdzJseGxnCitIWUg2UzROOVFSbXM4WTFZb1Yv
            b1o2bWVDNERBbzZHRFUybTNMYVM0eDAKLS0tIFNaWmVod01yTEZpSXV6VHZ6T0w1
            cnBOU3VLZHpxVk1Cc25MNDQ2WlZpVDgK/tv8pDLqsFnTXxYDTyP+W9NHYFDQ5TUq
            BbTGn9hetWjFXl+BcEEKIvZ4rTdH8gVwU2zAkqlkLemEndkw1DsxnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T04:28:04Z"
    mac: ENC[AES256_GCM,data:mY0MJMsrdTlMkRdzFe1zi+K3mV0uNjNGMF/y9u2/qh1mXP6kXS4hWmitAS1svsk0LgObbvJNZxEoTLPId4btP8BSZKzjaknz40fq0ENbsr5Nt3jKWDWn2bHj+OLyaTSF2vXcdoDJBHwT9dS8rJ+cRQrupZZ6ZBa3BPlp7e7ReIM=,iv:7ohmm8oRyuHFHC3bF/Jtv0LwRAtSrq3lyiKbiLG8rKM=,tag:bQLp/2GdR7ZKxyxFrxlkkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
