apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:y69kbjN/qyoquxQZSsUGWs3pGu/oqVHMkNYEJaqJdz/5fzw3freXFQ==,iv:Mjl2l/z23lfF7dLj+HJHprBwwKTuzl2cOmdcfDGXI+o=,tag:1aOAD4mAd1Ou6kF8h0WFug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlA5eGhvYUhBMXE5QktG
            NmhNeTYzZDVpYVJiT0x2aEtqRUNRR3BVV2pBClR1aXE0TER3WlUwcmN6YmJTS1Nq
            Zkk0Mlk4TENBSE9acEJqdXh4UGZFQncKLS0tIFF1M3NaejZSTWMxRTY2TVdnUUJm
            SEVVKyt3L0FaZWFJdFNKRmVTYU1WSVkK282sEFxiDwbL0SDQEW+UaWgeHsJpxHMo
            F5MWX8ONKqIR3oJbjv6mYDBVQ4ZyGLFiqxJlbgROke/MJlcW4e/eyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-17T04:05:50Z"
    mac: ENC[AES256_GCM,data:9FuA+GyUd/XBmA6M1WmGgOauZBAtGK6dKfN9r/wyQM9wFzSh9bpLvPQnl12VyXtH6UO75/x0FyZZsBwxsyVbrsxqqv4A8BFPHek15fsMs+tjZ918L9709PJvjHGVfH00ChBe/PEaC8E7MN9el7fl4ZsGXA4FFO7keQ09+oyeVj0=,iv:kawDSIVFLCA974S5m4ZPxMAEqm5AVR7F9huxOgQ6jhU=,tag:rCC+uCA6KuCquKm1h6Rhpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
