apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:wtRAeZUWV7GCbCS8lASXrt0jt6Zf7Ekyf4VPgUmUaH6wNKps3MQAsA==,iv:HMg9wRndqCue2KZpLVeym023WHq1wvBKq3+R11sTMw0=,tag:NW5VzmlwPmeDSWamN3pDtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WW5nNitPODV6cEVrSUlH
            U3RpeTgvenZuWDB2WDB5OEptU2RZbm5VZDBJCkZpK2ZiRlZramJWelduMVdKeWRi
            OGF3RHkxb1V4dk0rOXc4QTJDTVJQNk0KLS0tIHlmaDBla0Mrb1VCVHRUTkdBWnJh
            Z1JKTHZ0Y0FwS3dIeHJMVWdNY3EwOWMKeSXz0FRauYgnmziH2DMkizzjgeqqWTVm
            YUJ2gM46wi81ZJpQv4tbo2Gju3D7/u5fE0Gk6W99LWEPu1kcwxhR1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-16T03:20:14Z"
    mac: ENC[AES256_GCM,data:aO4cuiau2VDe4pVvTMK4aWwKyTyzXK7diWZui/e2pIDbUGuZ1PdbnGCRbnHPPCNP5avdv2cK2d16ZlaGsgEZYsYlK07MPDMIl3YBkl0MjEFv9unyDjLPQV4/oocADIsq5H2ETDUV4Q9xIyJ51i8cXH9xl+5M9cuA5c3Hx+uPhl4=,iv:VandUYUm6+/25uqGCD1ew8V/rCh44oVqvKoD/hMxYsM=,tag:DUYQpAIu8EHLdk8DYu+I4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
