apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:3Uvw+Td9Ign2KQ61X9Mwa+GILV3QrLkQQA5KLfcvzRQEM+f8aWY75A==,iv:IoBLAwKc/llXAerk7yZPQKvGsiFzW/rsH9eBs0sczDA=,tag:XaGdBK7Jyo8wDpA3ZMIp6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS2hSNnlTOHB4cStMTVZX
            ZExSVFdyRkEzTExTQ1RUVnRLN3VJcVg2L2pRCm13UUxDTmZ1OXVubUpuOHZJdFNk
            K2tsTGN3RTgxZ0NWcUNJc3hQalZJbTgKLS0tIFlEbEV4RTVUR1BNNUtoY2UzTWxt
            Ym1pVTZsZDRRS3BURmZ2K21xRUVMSEkKBBPfbHmMw2O08Wl0fmPwcD0GlC4c/at4
            MiCCAkkug0/hYtOQSEWZXkhia2q5XO2/j+/0b7e194/e54FViMfaGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T20:18:38Z"
    mac: ENC[AES256_GCM,data:qT5+s3eZ3soA9I+G4K3ZZyj0zncqOiznre5RQtygoPXkIE88+2CX7nsZljoT34ww8GlFlCIo8EiB3EeQMHfIedBnYwCXenW9qYJa8hGUhEgqmuBfvrWzNdJCmXR90TjR9fRBq7C5hpyqZxhJSU3BF3IuiZqZ9I+oQzluxTHVlQs=,iv:qyNeJWTQj05vJM6FcPcCgjc9q6C+fUu/PuT0E0qOtUA=,tag:2jxg7OcQfyvDJNdjnholog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
