apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:lfXtmttmoY6Ppls=,iv:7H+zgxTqPtTs8o9pCeybq5eSgeRiQcSnuHEyhqAOsQI=,tag:LoUqH4xA6eujrY+CuDWtfQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:scudHrhsQ132c5C/m/v6nb4=,iv:fccHj+sTHOVaqmME1nKUPLGxImNLnizPBFcpmIng55k=,tag:WFeoIsC5oICWOv0cUrmdBg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vUaXwjcCE0uwqiK0Q/Uq0y0E4tSjit4gYnDkojtQznPRBcNm,iv:EwfTB6Q+pkrtx+h3A/oVW99ZyoWjU1hqFycQo3PyHXg=,tag:CjpWnF9cavPVIbQmq8ZdWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OXhERUdLdWl5aTZ5aHg4
            UjQrNFRaQlN1T0QzRFRxOVFVbm5XeXZ0YUhjClVnVlRnOEZyK0wvY1RlNlZTcGYr
            UmplRmVJM2NjSFkwSEk0UmI2MndJTUUKLS0tIDJ4YmhYTDZ3UzlCSDlwVUF0VzhW
            WEVHZCtZc3ZkWi8xc1RDUVUyZytURDQKyC+HmcGiYOn9ynMuwiS3PlAQ0xpj80P5
            VhCDnt3yf/j5d8KPnVFyggFAOzg9yiXs6lU+4dX8IOHgfnIiAcobDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T21:15:37Z"
    mac: ENC[AES256_GCM,data:hXc0nnl/zkT7RzcPLvR2F1ixux54+Pktukn7wBGcNg/eGW8IA2AFioGUxwnsVS8QSsVxS0vF0FZo2gAuJMHRDYPENfdrCP2gM/vRtX8XNOUpIeodcIDb6+G6LZSA6D47G500uqaXxSNxzteLdl8PiYk33ZtIQU4KsRvSZ/2Cpm4=,iv:LszA1C78GsYEfPNhHSUmKj2aGlu0QskymlIFlkGFO7U=,tag:H0Wfv/gWq47bYZ2wcju4aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
