apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:UG1TrHu/e3kZKOc=,iv:jcd95amUVZLufnfXReqvSgqZQUy22UJ2wwxl6kglu5g=,tag:UjaEfO/9WAObWJXRA9rwZA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:5bvTslDbSzVjlfQJCZJZ2c0=,iv:TyYj+8Eb3OEAAm6CJScyHK4aGqHkvofaqU37HDILoOs=,tag:4Vtu/AjU6uRfcVBFX0Vh/w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:PSkux418tgpzEOwpz56WxlXOc+Xbqib5RloJg13tKhXC6Saz,iv:A8sLMxWb3BQUSI5gaN1SyiglHWBER1Wx7tGfui2emeU=,tag:8Ynh+j+lCDB5sJHfwBgbLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRlNVOGdOSHg3WE9YNDdz
            b2dPaDF2SDF5Y29HeWxoazJlL1ZwaDJpWEJnCjJ3R1Brc3Y5dHhvTWhXbjFVaUZC
            VVZjc2thVWNCUnRSMVdCV0oxRVpQVVkKLS0tIEcxbWFDUFRWYzJKZ3RTSHpmUVk2
            NWtiVnlSd2hjRkNOWjdJTHpkZHFtejgKqmw+s3IKI1jREGUEdmQ1WCO09TvUCkcz
            KIHoedhl8gyt0XWdMYLFYK9DwvUTtLdIsCNnN5bu3ET539M/FSH15Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-16T03:20:14Z"
    mac: ENC[AES256_GCM,data:aowgZLPfIqRcFTifmp5ah5MTY3L68hp1dhdUHksoEQ1XE/HW9D8a4VnucmWeUjvCjhdegJP7uAx2W6qX/zZ5gZvkCOzdOm8wz3Y6Mv+7hqKouuD4q/n1tF/Xq0bt92ngriu78+BfreiQlJ2XZ88hKc02hxfaumXRmmmCDAi9asA=,iv:KRi79b+ThyuV2xxutWXUDpShFOMiL3pg/qZ64cXIbbE=,tag:DIoMYxSAPQhDs1ZQsAVfsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
