apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:q38oN3dxBzQe1hQ=,iv:agfwrWSoAOhY4xMoIW/c6495vjp/VROfVYlEBmw0ic0=,tag:tos3StdmSBJ2cHnY9n5xXQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:vfyzSIp6Iy3HaAA/eMe7iyg=,iv:W/BKGnHqNNAe/oC19mN4lLIdMTiHzLgAvPSYRy1OYI4=,tag:iJ7sJrDfisbR0Rbt9BuLmA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:E0JMFUWH+YBwWiNdccboC6hlQby7xuii1fr6FQ8dBQ98ArPF,iv:1E93RUZ5ax9bRJIjffurJvb6y3+s2cKxOuj1t2aA6lQ=,tag:2uVKvWNRW7kAKRqYalGoTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWG1BcHlUMkN2Zkc2ZXpv
            aFFLNlNCYTVEeVpYbFFZU0RzQmVua0c3NTEwClJJVHMwdTZLdWpBTHhzcGVvallX
            MmV3RHVLM3hpN3p5dmo3MWRhdVZwaHMKLS0tIE9aV0ZrT09ZNGtodE1LdnY5alZy
            VUdKTmdFMWxzMGt4eDFuZTg2SHcxNTAKUrCzywW9uOMF2HaWXZE2tskSu0wIk8l6
            2/goFQaJMAWHN20thnwS9gyPunvffughmdIQ9T9iai4RuKGFfww7Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-17T04:05:50Z"
    mac: ENC[AES256_GCM,data:fnt/qlM2ggVsUET3oEQQpdXWoKvZXpYWZ/8nv7grLPWJptJF4ppv4tsXRkJ7L5Pn9thMxg501s2JcjEs+Qg3MJChSypKAonWkbVvA6OJNYqylbnqGFBZRPFrxda3nhXkUiWo0yuAUHfZzq1Qwn77Dm9icxjJoDPuw52Teg4Aws8=,iv:xfHYdgNh6WJ2RTcfMGV6l4Bx5Po1GuN4W6eTOgOGRwI=,tag:Mrk1/rnyJdhxCRBUqqhAdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
