apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:OKk/Z6/kORcg/sPtqvEsfjYDVqHkB19qJhXacZTQP1s=,iv:oDrsk3j57xFb5bGgmtd4Wi0Ka0RlDHa5UJsLsjyQt4Y=,tag:PmxiFewNyr4/F2a3HUoEmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQXlIbjFxV0RwNmh1cmM1
            NHZRZDZaM0RtVGtEaGJQcitjU2liV0QvbEg0CjVPdzFESTR1Wnp4UHRuRG1xRjhN
            VEgwK2N3QkJJMDd3Tjk5YUpPZDNIeGMKLS0tIGpkREIwM3hmZHpDMzkwVW1IQVY0
            cE12YU9wTmhTOVRLc01BbVZUbmpkMFUKUHP04ef8fid8A8SsHXjnx6OKbLW5+aj4
            3tGJ3pR5v8qiYBNJ5L8+t7RbhDIFnqGhNV4+WMGcZwHqczAfmrR4Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T20:41:44Z"
    mac: ENC[AES256_GCM,data:qm4sbophHI3fqDzXAyEjKvjfLpix1NNapDyZL/60oA8dk862SiJEpiJNh3Ihi6AN6nOPm9j4KdIbp9cdqe+d3CJ2RyZEMCNPeaOyBM6g5B4rClxZsAYBtbnlqLv4eXBDOifsk3Bgn4ApM3qVIt6kZ3Muca0wbvfusMD+saIg2IY=,iv:cC4ULdcrgkEKOvL4DeKqsJuCIslv+jo2hORNrxzUvPU=,tag:NpOSGR8Hy2pDlwCcbcS1yQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
