apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:e38Sedjy1y17DEwwNYUMck9I5FbtydeYQ5BeME0VQZ0=,iv:8X07g5Ek/i1IYEZfTXx6FFXgLmpgr5MDHxTLZWhWnd0=,tag:EUgrcZK9l8+yAxIYGmfafQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWS9QU0piUWh2Z0FEM2xk
            VnlyZEg0Z1cxamkrL3F4SEh6TzJLdjNsY1dBCjVJMDIvazZ3Z3FuVWU3VGhlVUUv
            dG1rUHpOR05pRU5zUUo5NnpWMmVRYnMKLS0tIHFhZ2UwQVNwanNOMnJtY0VlZTVr
            WkF0VTEveWRteWFUS09Hd3hmMFdJQUUKTM+FPmYyUcc5qX/McAFgc1stPVzdM/ii
            Vb3Fvv12t2XSU5ScIwaMwJ6SS+hA2DxnQ+e0FVocaRnhlnvG/kchgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T03:09:43Z"
    mac: ENC[AES256_GCM,data:JtuETNAzNLLl2RSPjdMFzRorB5/4RywOZi07q/sySpF+PCrv+IyFjoXmkclFME/QG2gqqnny4WLUEWcW2MlQlFPtX6htsAOpcae7SVJKlhlBC0ZmY38VcJhM+IGa/7zdmftCrJJ/VWuqwP2wbS011hAZSvtal5a+v7nwsZagPGc=,iv:nsXLE0yuBpoD3wU1Avo++hCzjfZ7bMsBsIhqbMeKp4k=,tag:FqfcTPf0oy4lVJWJ6fh9Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
