apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ZjBocBU+4zjVOCjQkOOVsrCevaKbeL7ajNFf/jta3cs=,iv:4fFS3kgOyeGIWVdhIPptNq7PQdwRBqNF+S4D9hpgf+Q=,tag:rfXu1zW+wOXEywAllqwfPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWWt4V3hjclArS3pmZ3Yx
            aFQwelM0VFFTUENjKzVkSjh6RmdEc3hrcTNvCnJYV2hNYlpTcjhJSHA3TU82U3hi
            MWErZUxVbGU0NENIM1NMNEpOdnRpeVEKLS0tIGkwOWJxdWp5a0x3aTFTb0tsMDVL
            V2dQTUV6a1BzNXhYRTBVY25CUldvME0KRCX1yp+Dy49KLy6sEr4+ZZg0SMDcalE1
            Jk8llSTb86yjBwetGEdh1cXCpkyQRxBQS4J5p9hK1kTjm1oaQ8Ydqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T04:28:04Z"
    mac: ENC[AES256_GCM,data:Kdgd2OrQkS33NVoypxrRh62+AWQtiNnXz1hL42G7arQUGcY5vvpB+H6PYTlvaa9/A5Ldulap5075AP3GYuHUuEB6YWV6/5hXgeUXsq6Hz9gqxm7RgW9f+bZVNqWeIchX7BBGEHN7W90jVPY6ueJgdd3zcyQTB3gAWDBio2KTdaM=,iv:V5j0n15UPkki+0UCG5Jr+71uCpm8RD3ee7i/qvMfv1I=,tag:bMKaDGPAHzdxRt47SHofaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
