apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:0rbGp5mAOucYSV42VQWXVsJZq7EE6o1qTrSOC7VAGXVayuBCJrgsVA==,iv:DOS0lw865p57/xaFBr59ngGXV4wJRuQEtijSlOB3idg=,tag:lp31fCkDCjYPo7btI9gn9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWS9VemdDNzFMUGx0SUUz
            dFBkNVE4Q1Urbm1hNWNSMzZvVG1rV0ExdXhrCmc1Q0p1cUtOZ3ZPazFXbVE5WWRX
            TzdkRXNST3ZpQUE1ZE5oNmJaM3ZwbkEKLS0tIElyanRWcit3Z2FWTDRlU0IydlhQ
            aFMyaHFtaXJSVU5GbW50eWR6eWNXK1EKnS4JtedIy7q9vz7lc4FX2Q3reufAu9UX
            E+7otWa5rZfxNJIpoP5av24X/RbJCconlZovLjj8ZnjNkXYYnXBhCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T05:17:59Z"
    mac: ENC[AES256_GCM,data:S1nWzPtPwTP40/VGeXmAoNqt8aY0Wg6p6aCbEL6KwUtE2xV3R7rDIjW2MrCy5WJKBee9Qfv+26Y3f384f1fHUi38HHqmhGH7h83Vq4/xvpY1WJR4boZq7CwW6Hlf1ZTxhojZIXi5XVaLKbJchzs0/7iewo7L+5XqiwbQzBMNjaI=,iv:albBEGsJBgSsWIG3qKiA+DbGGVO3bwkMJ5+9J+ICdEc=,tag:bT2aKPutrxC3t0wZ5rWiow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
