apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:xNFszBnd/c4pNB7F5R0BnroXBCwsuy3bAVSzaMlenvjY/ZGgJPVcoA==,iv:65RTsSs+D/xTDlkNO2FHQx8uKHGxKen5NL1/wuBfdRw=,tag:wmtPIWO3Iepor44uGm8EUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueVdoa09CNGFoV2ZhcFl4
            b2czQmtQZkl2Q0hTek56Z3hVZW1Kb3Z6QXc4CjVEQmRYTEJmRDNaZ0hNKzVUS2N5
            UkhLRkx6eThSeStobDRDVXV5VDcyUzgKLS0tIGZyOGpUTFVjeUNPTW1tTEw4RFAv
            YnczdlRJdkZzemJoWGNSeFdDU090R3cKWZfaQDaukib3w+qrYFNRLnwzsXZAtZcG
            +0Q83qbAXYq/6ghWVOP3BU2aN9mj13AgQdHXv8Fs+Zfo6Zool76oQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T01:53:36Z"
    mac: ENC[AES256_GCM,data:y2zrtUX1qcP3Kghef3SicGOh9W8o8RsscB1rHaILg09+zl7DOU+oqaUd9JxxO6qnYOgoWnh/nbb/XH+Ie0rALu0LhrCrevaSoBiB41o9gwjQA1k+8hybiJkw9UAZydE14hTQtoIamE/kNIEmSKhP1qEY5sTZie/7VGBczh7VznU=,iv:pTirMRgMh58hj+MlgubjhbYefscN03OEnte9DhHctvc=,tag:zJiSQ1l7IBA44NIzrHKULw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
