apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:flNVXWBVvBblGZ55ZdRega6+O0lBR3Z7mvfZrBq/o0w6jlEaFhDjLQ==,iv:EHAzZoWYzCX/Bom2BdQP3tMENHuGCVGmwULbjoO/T+c=,tag:scv7p9Wynsvhj3GW64inlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hmvep6d2673tugwpneaj3v5hkc4rlqq4f7z6an6lxapnp7qfvyzqc0zlhl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZGx2akdKcWFQK0luRXFL
            bm0wSGozb3RCNHZHZ0pmWDZ4eVFvYXpOMEVzCnBkOVMrUzJ5WWtoQUtLWkVCVFhX
            V2lteWdsK1M2MkVlVzlZdk5pL29SWWMKLS0tIGV0Zk1NbXQxTWZWekdPM1R3aGs2
            RU4xbG52UzJHWHNuMEtreDE4ZCszTEkK+BIBnI3XFpmgKbW5RQ7oLfIQXnUZXQE/
            nQMpoNMM2bv9kacEUG52hLiKQU3XWgZFb9qj7Vh2EQZrO1Gl9aIjrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T20:41:44Z"
    mac: ENC[AES256_GCM,data:0t8vycILzYgtNXBlgZ8v39LmCdr+vQFCzDoVyOjHt4i333hyWRu5ZxJPUdf8JSonXqnecI7EIqbJ200F7bqWXJUudEsc1IfxsQ2VcAuYBjeWvLkfxnxLU2EYnnl5W+AF37YzLmIQINjw32VkNUog0IEVMvmtszmRpUxXnEO+UAY=,iv:8ChSRRKOZdnOFimDo0ygH0tnpfqO/fWgiYfXkg8LH0c=,tag:aCZcxp2GR7dM1sCucfJ+zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
